36 할 일 목록 now now 구현하기
extreme-todo/frontend pull request #53
Opened 2024-02-23 07:35 UTC by ferrariRoma

질문이 몇 가지 있습니다.

1. 지난 번에 `duration`에는 토마토 갯수만 저장한다고 했던 기억이 납니다! 만약 제 기억이 맞다면 `duration`에 'usePomodoro'를 사용해서 현재 집중 단위(?) 가지고 와서 곱하면 될까요? 현재는 'duration' 자체를 ms 값으로 가정하고 작업을 했습니다.
2. 저희 todo 데이터의 시간이 ms 단위가 맞을까요? `NowCard.tsx`에서 ms를 기준으로 해서 시간, 분 변환 로직을 만들었습니다.
3. `TodoList.tsx`에서 `useCurrentTodo` 훅을 사용해서 현재 할 일에 대한 정보를 가져왔습니다. 이렇게 사용하면 될까요?..

질문 문답 이후 수정하겠습니다. 코멘트 남겨주세요 :)

2024-02-25 02:44 UTC, imhjnoh commented
> 질문이 몇 가지 있습니다.
> 
> 1. 지난 번에 `duration`에는 토마토 갯수만 저장한다고 했던 기억이 납니다! 만약 제 기억이 맞다면 `duration`에 'usePomodoro'를 사용해서 현재 집중 단위(?) 가지고 와서 곱하면 될까요? 현재는 'duration' 자체를 ms 값으로 가정하고 작업을 했습니다.
> 2. 저희 todo 데이터의 시간이 ms 단위가 맞을까요? `NowCard.tsx`에서 ms를 기준으로 해서 시간, 분 변환 로직을 만들었습니다.
> 3. `TodoList.tsx`에서 `useCurrentTodo` 훅을 사용해서 현재 할 일에 대한 정보를 가져왔습니다. 이렇게 사용하면 될까요?..
> 
> 질문 문답 이후 수정하겠습니다. 코멘트 남겨주세요 :)

1. duration에는 별다른 연산 없이 "오직" 토마토 개수만 저장해두면 됩니다! 토마토가 몇 분을 의미하는지 알고싶은 것이라면 usePomodoro를 사용하여 focusStep(분단위)를 곱하고, 6000ms(1분) 를 곱하면 ms단위 시간을 만들 수 있습니다.
2. 제가 지금 디자인을 보니.. 바꾸는 걸 까먹었네요😭 NowCard에도 토마토 개수만 들어가게 하려고 했었는데, 계산 로직을 만들어주셨으니 그대로 가도 좋을 것 같습니다..👍
3. 넵 useCurrentTodo 사용해주시면 됩니다🙇‍♂️

2024-02-25 02:47 UTC, imhjnoh requested changes

2024-02-25 02:47 UTC, imhjnoh commented on src/hooks/useCurrentTodo.ts
> +      duration: 60 * 30 * 100,
옛날버전입니다 PR 빨리 올리지 않아서 죄송합니다..ㅠ 여기에는 토마토 개수만 들어갑니다.

2024-02-25 02:47 UTC, imhjnoh commented on src/molecules/NowCard.tsx
> +  const time = timeH() + timeM();
시간로직도 아마 수정이 필요하겠네요..😭

2024-02-29 18:03 UTC, ferrariRoma commented
@imhjnoh 말씀 주셨던 부분 모두 수정했습니다. 확인하시고 더 수정해야 하는 부분 있으면 코멘트 남겨주세요 :)

2024-03-04 11:20 UTC, imhjnoh approved these changes

2024-03-04 11:21 UTC, merged